package com.pcplanet.exception;

public enum ErrorCode {
    NOT_FOUND(404),
    ACCESS_DENIED(403),
    PRODUCT_NOT_FOUND(4011),
    NO_PRODUCT_ID_PROVIDED(4012),
    NO_BRAND_FOUND(4013),
    NO_CATEGORY_FOUND(4014),
    NO_SUB_CATEGORY_FOUND(4025),
    NO_KEY_FEATURE_FOUND(4015),
    NO_BRAND_SELECTED(4016),
    NO_CATEGORY_SELECTED(4017),
    NO_PRODUCT_STATUS_SELECTED(4018),
    NO_PRODUCT_NAME_PROVIDED(4019),
    NO_PRODUCT_CODE_PROVIDED(4020),
    NO_PRODUCT_MODEL_PROVIDED(4021),
    NO_PRODUCT_PRICE_PROVIDED(4022),
    INVALID_PRODUCT_CODE_SIZE(4023),

    CATEGORY_ALREADY_EXISTS(4024),
    SUB_CATEGORY_ALREADY_EXISTS(4024),
    BRAND_ALREADY_EXISTS(4024),
    PRODUCT_ATTRIBUTE_ALREADY_EXISTS(4024),
    PRODUCT_ATTRIBUTE_VALUE_ALREADY_EXISTS(4026),

    INTERNAL_SERVER_ERROR(999);

    public final int value;

    ErrorCode(int value) {
        this.value = value;
    }
}
