package com.pcplanet.exception;

public enum ErrorCode {
    NOT_FOUND(404),
    ACCESS_DENIED(403),

    PRODUCT_NOT_FOUND(4011),
    BRAND_NOT_FOUND(4012),
    CATEGORY_NOT_FOUND(4013),
    SUB_CATEGORY_NOT_FOUND(4014),
    PRODUCT_KEY_FEATURE_NOT_FOUND(4015),
    PRODUCT_ATTRIBUTE_NOT_FOUND(2016),
    PRODUCT_ATTRIBUTE_VALUE_NOT_FOUND(2017),

    NO_PRODUCT_ID_PROVIDED(4031),
    NO_BRAND_SELECTED(4032),
    NO_CATEGORY_SELECTED(4033),
    NO_PRODUCT_STATUS_SELECTED(4034),
    NO_PRODUCT_NAME_PROVIDED(4035),
    NO_PRODUCT_CODE_PROVIDED(4036),
    NO_PRODUCT_MODEL_PROVIDED(4037),
    NO_PRODUCT_PRICE_PROVIDED(4038),

    CATEGORY_ALREADY_EXISTS(4051),
    SUB_CATEGORY_ALREADY_EXISTS(4052),
    BRAND_ALREADY_EXISTS(4053),
    PRODUCT_ATTRIBUTE_ALREADY_EXISTS(4054),
    PRODUCT_ATTRIBUTE_VALUE_ALREADY_EXISTS(4055),

    INVALID_PRODUCT_CODE_SIZE(4071),

    INTERNAL_SERVER_ERROR(999);

    public final int value;

    ErrorCode(int value) {
        this.value = value;
    }
}
