INSERT INTO brand (id, name) values (1, 'ASUS');
INSERT INTO brand (id, name) values (2, 'SONY');
INSERT INTO brand (id, name) values (3, 'MSI');
INSERT INTO brand (id, name) values (4, 'INTEL');
INSERT INTO brand (id, name) values (5, 'CANON');
INSERT INTO brand (id, name) values (6, 'APOLLO');
INSERT INTO brand (id, name) values (7, 'POWER GUARD');
INSERT INTO brand (id, name) values (8, 'AMD');
INSERT INTO brand (id, name) values (9, 'GIGABYTE');
INSERT INTO brand (id, name) values (10, 'ZOTAC');
INSERT INTO brand (id, name) values (11, 'LG');
INSERT INTO brand (id, name) values (12, 'HP');
INSERT INTO brand (id, name) values (13, 'Colorful');
INSERT INTO brand (id, name) values (14, 'Nikon');
INSERT INTO brand (id, name) values (15, 'Panasonic');
INSERT INTO brand (id, name) values (16, 'ASRock');
INSERT INTO brand (id, name) values (17, 'MaxGreen');
INSERT INTO brand (id, name) values (18, 'SANTAK');
INSERT INTO brand (id, name) values (19, 'Apple');
INSERT INTO brand (id, name) values (20, 'Dell');
INSERT INTO brand (id, name) values (21, 'Acer');
INSERT INTO brand (id, name) values (22, 'Lenovo');
INSERT INTO brand (id, name) values (23, 'Samsung');
INSERT INTO brand (id, name) values (24, 'Transcend');
INSERT INTO brand (id, name) values (25, 'Corsair');
INSERT INTO brand (id, name) values (26, 'G.Skill');
INSERT INTO brand (id, name) values (27, 'MARSRIVA');
INSERT INTO brand (id, name) values (28, 'DJI');
INSERT INTO brand (id, name) values (29, 'GoPro');
INSERT INTO brand (id, name) values (30, 'Razer');
INSERT INTO brand (id, name) values (31, 'Logitech');

SELECT setval('brand_id_seq', 31, true);